#SPDX-License-Identifier: MIT-0
---
# tasks file for roles/front
- name: Run Frontend Application
  docker_container:
    name: frontend-app
    image: martindmv/my-frontend:latest
    pull: always
    networks:
      - name: app-network