#SPDX-License-Identifier: MIT-0
---
# tasks file for roles/app
- name: Run Application
  docker_container:
    name: backend-api
    image: martindmv/my-simple-api:latest
    networks:
      - name: app-network
      - name: db-network
    env:
      DB_URL: "jdbc:postgresql://my3tierapp:5432/{{ DB_NAME }}"
      DB_USER: "{{ DB_USER }}"
      DB_PASSWORD: "{{ DB_PASSWORD }}"