name: Deploy

on:
  workflow_run:
    workflows: ["Backend CD"]
    types:
      - completed
    branches:
      - main # S'exécute UNIQUEMENT si le workflow CD a tourné sur la branche main

jobs:
  deploy-to-server:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup SSH Connection
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          # On ajoute l'IP du serveur aux hôtes connus pour éviter que le terminal GitHub ne bloque
          ssh-keyscan -H ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts

      - name: Install Ansible
        run: sudo apt-get update && sudo apt-get install -y ansible

      - name: Run Ansible Playbook
        env:
          # On injecte les secrets GitHub dans l'environnement virtuel du runner
          DB_NAME: ${{ secrets.DB_NAME }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        run: |
          cd ansible
          ansible-playbook -i inventories/setup.yml playbook.yml